version: "3.4"

services:
  neo4j:
    image: neo4j:4.0.4
    volumes:
      - ./dbms/data:/data
      - ./dbms/logs:/logs
    environment:
      - NEO4J_AUTH=neo4j/admin
    ports:
      - 7474:7474
      - 7687:7687
