version: "3.8"

services:
  reconf:
    image: reconf
    build:
      context: ./reconf/
      dockerfile: Dockerfile
    volumes:
      - ./reconf:/usr/bin/reconf
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /usr/bin/reconf
    depends_on:
      - neo4j
      - mosquitto
  neo4j:
    image: neo4j:4.0.4
    # for debugging
    #volumes:
    #  - ./neo4j/dbms/data:/data
    #  - ./neo4j/dbms/logs:/logs
    environment:
      - NEO4J_AUTH=neo4j/admin
    ports:
      - 7474:7474
      - 7687:7687
  mosquitto:
    image: eclipse-mosquitto:2.0.5
    ports:
      - 1883:1883
    volumes:
      # read-only mosquitto config
      - ./mosquitto:/mosquitto/config:ro
