version: "3.8"

services:
  reconf:
    image: reconf-container
    init: true
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    volumes:
      - ./:/usr/src/app
      - /var/run/docker.sock:/var/run/docker.sock
      - ../services:/usr/src/app/services
    working_dir: /usr/src/app
    command: ["node", "dist/app.js"]
  neo4j:
    image: neo4j:4.0.4
    volumes:
      - ./dbms/data:/data
      - ./dbms/logs:/logs
    environment:
      - NEO4J_AUTH=neo4j/admin
    ports:
      - 7474:7474
      - 7687:7687
  mosquitto:
    image: eclipse-mosquitto:1.6.9
    ports:
      - 1883:1883
