version: "3.4"

services:
  reconf:
    image: node:14-alpine
    environment:
      NODE_ENV: production
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: ["node", "dist/app.js"]
