version: "3.8"

services:
  reconf:
    image: reconf-container
    init: true
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    volumes:
      - ./:/usr/src/app
      - /var/run/docker.sock:/var/run/docker.sock
      - ../services:/usr/src/app/services
    working_dir: /usr/src/app
    command: ["node", "dist/app.js"]
